import { getStore } from '@netlify/blobs';
import * as XLSX from 'xlsx';

const json = (obj, status=200) => new Response(JSON.stringify(obj), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const norm = (v='') => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim().replace(/\s+/g,' ');
const HEADER_MAP={
  'COMPANIA':'COMPAÑÍA','IAFA':'COMPAÑÍA','ASEGURADORA':'COMPAÑÍA','FINANCIADOR':'COMPAÑÍA',
  'SUB CIA':'SUB CIA','SUBCIA':'SUB CIA','SUB COMPANIA':'SUB CIA','PRODUCTO':'SUB CIA','PLAN':'SUB CIA',
  'ID':'ID','CODIGO':'ID','CODIGO ID':'ID','COD':'ID','LISTA':'LISTA','TIPO LISTA':'LISTA','LISTA AB':'LISTA',
  'TECNOLOGIA':'TECNOLOGÍA','PRESTACION':'TECNOLOGÍA','DESCRIPCION':'TECNOLOGÍA','SERVICIO':'TECNOLOGÍA','PROCEDIMIENTO':'TECNOLOGÍA','SERVICIO O PROCEDIMIENTO':'SERVICIO O PROCEDIMIENTO',
  'COBERTURA':'COBERTURA','ESTADO COBERTURA':'COBERTURA','CONDICIONES':'CONDICIONES','CONDICION':'CONDICIONES','EXCEPCIONES':'EXCEPCIONES','EXCEPCION':'EXCEPCIONES',
  'DETALLES':'DETALLES','DETALLE':'DETALLES','OBSERVACIONES':'DETALLES','OBSERVACION':'DETALLES','PALABRAS CLAVE':'PALABRAS CLAVE','KEYWORDS':'PALABRAS CLAVE',
  'REQUIERE CG':'REQUIERE CG','CARTA DE GARANTIA':'REQUIERE CG','REQUIERE CARTA DE GARANTIA':'REQUIERE CG','CONDICIONES / EXCEPCIONES':'CONDICIONES / EXCEPCIONES','CONDICIONES/EXCEPCIONES':'CONDICIONES / EXCEPCIONES'
};
function rowsFromSheet(ws){ return XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false}); }
function inferCompany(name){const n=norm(name);for(const c of ['MAPFRE','PACIFICO','RIMAC','SANITAS','LA POSITIVA','POSITIVA'])if(n.includes(c))return ({PACIFICO:'Pacífico',RIMAC:'Rímac',MAPFRE:'Mapfre',SANITAS:'Sanitas','LA POSITIVA':'La Positiva',POSITIVA:'Positiva'})[c];return '';}
function parseListas(wb){const records=[];for(const sheetName of wb.SheetNames){const rows=rowsFromSheet(wb.Sheets[sheetName]);let hi=-1,mapping={};for(let i=0;i<Math.min(rows.length,25);i++){const cand={};rows[i].forEach((v,j)=>{const k=HEADER_MAP[norm(v)];if(k)cand[j]=k;});const vals=Object.values(cand);if((vals.includes('TECNOLOGÍA')||vals.includes('SERVICIO O PROCEDIMIENTO'))&&(vals.length>=3||vals.includes('LISTA'))){hi=i;mapping=cand;break;}}if(hi<0)continue;const sc=inferCompany(sheetName);for(const row of rows.slice(hi+1)){const rec={};for(const [j,k] of Object.entries(mapping))rec[k]=String(row[Number(j)]??'').trim();if(!rec['TECNOLOGÍA']&&rec['SERVICIO O PROCEDIMIENTO'])rec['TECNOLOGÍA']=rec['SERVICIO O PROCEDIMIENTO'];if(!rec['SERVICIO O PROCEDIMIENTO']&&rec['TECNOLOGÍA'])rec['SERVICIO O PROCEDIMIENTO']=rec['TECNOLOGÍA'];if(!rec['TECNOLOGÍA'])continue;if(!rec['COMPAÑÍA']&&sc)rec['COMPAÑÍA']=sc;for(const k of ['COMPAÑÍA','SUB CIA','ID','LISTA','COBERTURA','CONDICIONES','EXCEPCIONES','DETALLES','PALABRAS CLAVE','REQUIERE CG'])rec[k]=rec[k]||'';if(!rec['CONDICIONES / EXCEPCIONES'])rec['CONDICIONES / EXCEPCIONES']=[rec.CONDICIONES&&`Condiciones: ${rec.CONDICIONES}`,rec.EXCEPCIONES&&`Excepciones: ${rec.EXCEPCIONES}`].filter(Boolean).join('\n');records.push(rec);}}
 if(!records.length)throw new Error('No se detectaron filas válidas de LISTAS AB. Verifica los encabezados.');return records;}
function headerMap(rows){for(let i=0;i<Math.min(rows.length,20);i++){const mp={};rows[i].forEach((v,j)=>{if(String(v||'').trim())mp[norm(v)]=j;});if(mp.ID!==undefined&&mp.IAFA!==undefined&&mp['PREGUNTA O SITUACION']!==undefined&&mp['RESPUESTA / REGLA']!==undefined)return [i,mp];}return [-1,{}];}
function cell(row,mp,...names){for(const n of names){const j=mp[norm(n)];if(j!==undefined)return String(row[j]??'').trim();}return '';}
function parseCap(wb){const wsName=wb.SheetNames.find(n=>norm(n)==='CAPACITACIONES');if(!wsName)throw new Error('No se encontró la hoja CAPACITACIONES.');const rows=rowsFromSheet(wb.Sheets[wsName]);const [hi,mp]=headerMap(rows);if(hi<0)throw new Error('La hoja CAPACITACIONES no tiene los encabezados esperados.');const records=[];for(const row of rows.slice(hi+1)){const id=cell(row,mp,'ID'),iafa=cell(row,mp,'IAFA'),producto=cell(row,mp,'Producto'),tema=cell(row,mp,'Tema'),pregunta=cell(row,mp,'Pregunta o situación'),respuesta=cell(row,mp,'Respuesta / Regla'),accion=cell(row,mp,'Qué hacer'),fuente=cell(row,mp,'Fuente'),pagina=cell(row,mp,'Página'),estado=norm(cell(row,mp,'Estado'));if(!respuesta||['INACTIVO','BORRADOR','ELIMINADO'].includes(estado))continue;records.push({id:id||`CAP-${String(records.length+1).padStart(5,'0')}`,tipo_registro:'CAPACITACION',iafas:iafa||'Institucional',producto:producto||'General',grupo:tema||'General',categoria:tema||'General',tema:tema||pregunta,pregunta:pregunta||tema,respuesta,resumen:respuesta,accion,decision:accion,revisar:'',alerta:'',alertas:'',fuente:fuente||'Maestro de Capacitaciones IAFAS',pagina:pagina||'-',pagelink:pagina||'',pdf:'',archivo_fuente:'',keywords:[iafa,producto,tema,pregunta,respuesta,accion,fuente].join(' '),aliases:'',origen_maestro:'CAPACITACIONES'});}if(!records.length)throw new Error('No se detectó información publicable en el maestro de Capacitaciones.');return records;}
function companies(records,type){const key=type==='capacitaciones_master'?'iafas':'COMPAÑÍA';const out={};for(const r of records){const c=r[key]||'Sin IAFA';out[c]=(out[c]||0)+1;}return out;}
function parseWorkbook(base64,type='auto'){const wb=XLSX.read(Buffer.from(base64,'base64'),{type:'buffer'});if(type==='capacitaciones_master')return {type,records:parseCap(wb)};if(type==='listas_ab')return {type,records:parseListas(wb)};try{return {type:'capacitaciones_master',records:parseCap(wb)}}catch(_){return {type:'listas_ab',records:parseListas(wb)}}}
export default async (req) => {try{const url=new URL(req.url);const action=url.searchParams.get('action')||'sources';if(action==='health')return json({ok:true,service:'source-center',version:'4.2.138'});const store=getStore('iafas-hub-sources');if(req.method==='GET'){
  if(action==='data'){const type=url.searchParams.get('type')||'listas_ab';const payload=await store.get(`current/${type}`,{type:'json',consistency:'strong'});return json({ok:true,payload});}
  const list=await store.get('meta/sources',{type:'json',consistency:'strong'})||{};const history=await store.get('meta/history',{type:'json',consistency:'strong'})||[];return json({ok:true,sources:[{type:'listas_ab',label:'LISTAS AB',current:list.listas_ab||{}},{type:'capacitaciones_master',label:'Maestro de Capacitaciones IAFAS',current:list.capacitaciones_master||{}},{type:'peas',label:'PEAS',current:{}},{type:'manual',label:'Manual de Normas',current:{}},{type:'capacitacion',label:'Capacitación / documento IAFA',current:{documents:0}}],history});}
  const body=await req.json();if(action==='preview'){if(!body.content)throw new Error('No se recibió el archivo Excel.');const parsed=parseWorkbook(body.content,body.type||'auto');const uid=crypto.randomUUID();const comps=companies(parsed.records,parsed.type);await store.setJSON(`pending/${uid}`,{type:parsed.type,filename:body.filename||'fuente.xlsx',records:parsed.records,created_at:new Date().toISOString()});const meta=await store.get('meta/sources',{type:'json',consistency:'strong'})||{};return json({ok:true,preview:{upload_id:uid,type:parsed.type,label:parsed.type==='listas_ab'?'LISTAS AB':'Maestro de Capacitaciones IAFAS',filename:body.filename||'fuente.xlsx',bytes:Math.round((body.content.length*3)/4),current:meta[parsed.type]||{},detail:{records:parsed.records.length,companies:comps,warning:''}}});}
  if(action==='publish'){const p=await store.get(`pending/${body.upload_id}`,{type:'json',consistency:'strong'});if(!p)throw new Error('La vista previa expiró. Vuelve a seleccionar el Excel.');const old=await store.get(`current/${p.type}`,{type:'json',consistency:'strong'});const stamp=Date.now();if(old)await store.setJSON(`backup/${p.type}/${stamp}`,old);const payload={records:p.records,filename:p.filename,version:body.version||'',title:body.title||'',company:body.company||'',published_at:new Date().toISOString()};await store.setJSON(`current/${p.type}`,payload);const meta=await store.get('meta/sources',{type:'json',consistency:'strong'})||{};const comps=companies(p.records,p.type);meta[p.type]={filename:p.filename,records:p.records.length,companies:Object.keys(comps).length,modified:payload.published_at,version:body.version||''};await store.setJSON('meta/sources',meta);const history=await store.get('meta/history',{type:'json',consistency:'strong'})||[];history.unshift({id:String(stamp),type:p.type,label:p.type==='listas_ab'?'LISTAS AB':'Maestro de Capacitaciones IAFAS',filename:p.filename,version:body.version||'',published_at:payload.published_at,status:'published',backup:old?String(stamp):''});await store.setJSON('meta/history',history.slice(0,30));await store.delete(`pending/${body.upload_id}`);return json({ok:true,registros:p.records.length,companies:Object.keys(comps)});}
  if(action==='restore'){const history=await store.get('meta/history',{type:'json',consistency:'strong'})||[];const ev=history.find(x=>x.id===String(body.event_id||''));if(!ev||!ev.backup)throw new Error('No se encontró respaldo para esa versión.');const backup=await store.get(`backup/${ev.type}/${ev.backup}`,{type:'json',consistency:'strong'});if(!backup)throw new Error('El respaldo ya no está disponible.');const current=await store.get(`current/${ev.type}`,{type:'json',consistency:'strong'});const stamp=Date.now();if(current)await store.setJSON(`backup/${ev.type}/${stamp}`,current);backup.published_at=new Date().toISOString();await store.setJSON(`current/${ev.type}`,backup);const meta=await store.get('meta/sources',{type:'json',consistency:'strong'})||{};const comps=companies(backup.records||[],ev.type);meta[ev.type]={filename:backup.filename||ev.filename,records:(backup.records||[]).length,companies:Object.keys(comps).length,modified:backup.published_at,version:backup.version||''};await store.setJSON('meta/sources',meta);history.unshift({id:String(stamp),type:ev.type,label:ev.label,filename:backup.filename||ev.filename,version:backup.version||'',published_at:backup.published_at,status:'restored',backup:current?String(stamp):''});await store.setJSON('meta/history',history.slice(0,30));return json({ok:true});}
  return json({ok:false,error:'Acción no disponible.'},404);
}catch(e){return json({ok:false,error:`Centro de Fuentes: ${e?.message||String(e)}`},500)}};
